package com.masterteknoloji.net.domain.enumeration;

/**
 * The AlarmType enumeration.
 */
public enum AlarmType {
    LEAVE_POST, FIGHT, ELECTRIC_BIKE_IN_ELEVATOR, EXIT, PARK, RETROGRADE, PERSON_OVER_QUERYING, PERSON_LESS_QUERYING, GATHERING, SMOKING, RUN, CALL, FALL, WATCH_PHONE, SLEEP, HOLDWEAPON, COLLISION, INTRUSION, TRIPWIRE, OVERWALL, CLIMB, WANDER, MAX_NUMBER_PEOPLE, CROSS_LINE, SAFETY_CAP, SAFETY_UNIFORM, SAFETY_BELT, REFLECTIVE_VEST, RESPIRATOR, FIRE, SMOKE, OIL_SPILL, FIRE_EQUIPMENT
}
