version: '2'
services:
    safeworking-app:
        image: safeworking
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://safeworking-mysql:3306/safeworking?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    safeworking-mysql:
        extends:
            file: mysql.yml
            service: safeworking-mysql
